name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Private Actions Checkout
        uses: daspn/private-actions-checkout@v2.4
      - name: Verify Java version
        run: echo java -version
