name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4.1.7
      - name: Setup AdoptOpenJDK
        uses: joschi/setup-jdk@v2.5.1



