name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4.1.7

      - name: Setup AdoptOpenJDK
        uses: joschi/setup-jdk@v2.5.1
        with:
          java-version: '17'

      - name: Download and set up ChromeDriver
        run: |
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
            unzip -q /tmp/chromedriver_linux64.zip -d /tmp/
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test



