name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Private Actions Checkout
        uses: daspn/private-actions-checkout@v2.4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
