name: First Workflow
on:
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: echo "Printing greeting"
      - name: Print Goodbye
        run: echo "Printing Goodbye"