name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting message
        run: echo "Print Greeting step executed"
      - name: Print Goodbye message
        run: echo "Print Goodbye step executed"

